### ISSUE TITLE
Close stream if exception happens / handle file exceptions

### ISSUE THREAD

**Issue by kristof12345** [kristof12345/SzamitogepBiztonsagHF#1]
https://github.com/kristof12345/SzamitogepBiztonsagHF/blob/6e55de8d5a4f9de4ba79b7f480356abc5f53d865/CAFFparser/CAFFparser/caff.cpp#L220

Shouldn't we add a try-catch block for file handling? I think, if the file cannot be created/opened this throws an exception.

**Comment by bargergo** [comment]
In C++ iostreams don't throw exceptions by default [see here](https://stackoverflow.com/questions/3629321/try-catch-block-for-c-file-io-errors-not-working)

I implemented a check to make sure the file opened successfully.
77706aa21ae177534d83d895221699effcc36826

**Comment by kristof12345** [comment]
Thanks. Checked it and you're right. The new implementation seems correct.
